# Generated by Django 3.2.8 on 2021-11-21 12:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0007_auto_20211121_1338'),
        ('structure', '0004_houses_transformer_levy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceChargePayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident', models.CharField(max_length=30)),
                ('payment_date', models.DateField(default=datetime.date, null=True, verbose_name='pay_date')),
                ('payment_note', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Payment Verified'), (0, 'Verification Pending')], default=0, verbose_name='payment_status')),
                ('payment_ref', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransformerLevyPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident', models.CharField(max_length=30)),
                ('payment_date', models.DateField(default=datetime.date, null=True, verbose_name='pay_date')),
                ('payment_note', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Payment Verified'), (0, 'Verification Pending')], default=0, verbose_name='payment_status')),
                ('payment_ref', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResidentFinancialStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_charge_outstanding', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transformer_levy_outstanding', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='residents.residents', to_field='resident_code')),
            ],
        ),
        migrations.CreateModel(
            name='ChargesDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transformer_levy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('housetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.housetype', to_field='htype')),
            ],
        ),
    ]
