# Generated by Django 3.2.8 on 2021-12-01 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0004_houses_transformer_levy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='structure.houses', to_field='housecode')),
            ],
        ),
    ]
