# Generated by Django 3.2.8 on 2021-12-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_accrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Payment Verified'), (0, 'Verification Pending'), (2, 'Request Cancelled')], default=0, verbose_name='request_status'),
        ),
    ]
