# Generated by Django 3.2.8 on 2021-10-28 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_auto_20211023_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityheads',
            name='date_appointed',
            field=models.DateField(default=datetime.date, null=True, verbose_name='start_date'),
        ),
        migrations.AlterField(
            model_name='residents',
            name='mobile_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='residents',
            name='occupancy_start',
            field=models.DateField(default=datetime.date, null=True, verbose_name='occ_start'),
        ),
        migrations.AlterField(
            model_name='residents',
            name='resident_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
