# Generated by Django 3.2.8 on 2021-11-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_auto_20211028_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytypes',
            name='property_code',
            field=models.CharField(default='KGERA', max_length=10, null=True),
        ),
    ]
