# Generated by Django 3.2.8 on 2021-11-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0005_auto_20211120_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='property_type',
            field=models.CharField(choices=[('VHL', 'Motor Vehicle'), ('ACN', 'Air Condition'), ('GEN', 'Generator Set'), ('SLR', 'Solar Inverter Set'), ('FRT', 'Furniture'), ('MTL', 'Metal Works e.g Metal Cage'), ('KTCH', 'Kitchen Appliance e.g Oven'), ('OTH', 'Others, Please Specify')], default='VHL', max_length=10),
        ),
    ]
