# Generated by Django 3.2.8 on 2021-11-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0006_alter_properties_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='property_type',
            field=models.CharField(choices=[('VHL', 'Motor Vehicle'), ('ACN', 'Air Conditioner'), ('GEN', 'Generator Set'), ('SLR', 'Solar Inverter Set'), ('FRT', 'Furniture'), ('MTL', 'Metal Works e.g Metal Cage'), ('KTCH', 'Kitchen Appliance e.g Oven'), ('OTH', 'Others, Please Specify')], default='VHL', max_length=10),
        ),
        migrations.AlterField(
            model_name='residents',
            name='resident_code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
