# Generated by Django 3.2.8 on 2021-12-01 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0008_alter_residents_occupancy_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residents',
            name='occupancy_start',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='occ_start'),
        ),
    ]
