# Generated by Django 3.2.8 on 2021-12-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0010_residents_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residents',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='residents',
            name='occupancy_end',
            field=models.DateField(blank=True, null=True, verbose_name='occ_end'),
        ),
    ]
