# Generated by Django 3.2.8 on 2021-12-03 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_house'),
        ('residents', '0011_auto_20211203_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residents',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
