# Generated by Django 3.2.8 on 2021-12-03 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_house'),
        ('residents', '0012_alter_residents_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residents',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
