# Generated by Django 3.2.7 on 2021-10-04 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commnum', models.IntegerField(default=1)),
                ('commcode', models.CharField(max_length=5, unique=True, verbose_name='Community Code')),
            ],
        ),
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htype', models.CharField(max_length=200, unique=True, verbose_name='House Type')),
                ('is_block', models.BooleanField(default=False)),
                ('block_count', models.PositiveSmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten')], default=1)),
                ('is_flat', models.BooleanField(default=False)),
                ('flat_count', models.PositiveSmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housecode', models.CharField(max_length=200, unique=True)),
                ('housestatus', models.PositiveSmallIntegerField(choices=[(0, 'Vacant'), (1, 'Occupied')], default=0)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.community')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commtype', models.CharField(default='A', max_length=3, verbose_name='Community Type Code')),
                ('description', models.TextField(default='Description of the Community Type')),
                ('housetype', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='structure.housetype')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='communitytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.communitytype'),
        ),
    ]
