# Generated by Django 3.2.8 on 2021-10-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housetype',
            name='block_count',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten')], default=1),
        ),
        migrations.AlterField(
            model_name='housetype',
            name='flat_count',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten')], default=1),
        ),
    ]
