# Generated by Django 3.2.8 on 2021-10-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20211018_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitytype',
            name='commtype',
            field=models.CharField(default='A', max_length=3, unique=True, verbose_name='Community Type Code'),
        ),
    ]
