# Generated by Django 3.2.8 on 2021-11-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_alter_communitytype_commtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='transformer_levy',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Paid'), (0, 'Unpaid'), (2, 'Payment Uncompleted')], default=1),
        ),
    ]
