# Generated by Django 3.2.8 on 2021-12-01 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_houses_transformer_levy'),
        ('accounts', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='structure.houses', to_field='housecode'),
        ),
    ]
